taco:
  orders:
    pageSize: 10

---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacoloud
    username: tacodb
    password: tacopassword
    driver-class-name: com.mysql.jdbc.Driver
    schema:
    - order-schema.sql
    - ingredient-schema.sql
    - taco-schema.sql
    - user-schema.sql
    data:
    - ingredients.sql  
 
server:
  port: 8443
  ssl:
    key-store: file://Users/gunjun/Github/spring_project/taco-cloud/mykeys.jks
    key-store-password: abcde12#
    key-password: abcde12#

logging:
  file: 
    path: /var/logs/
    max-size: 500MB
  level: 
    root: WARN
    org:
      springframework:
        security: DEBUG